#!/usr/bin/env python3
"""Control class for the MSTM Model Manager

"""

import os

__author__ = 'Carey Legett'
__copyright__ = 'Copyright 2018, Stony Brook University'
__credits__ = ['Carey Legett']

__version__ = '1.0'
__maintainer__ = 'Carey Legett'
__email__ = 'carey.legett@stonybrook.edu'
__status__ = 'Production'

def read_packlsd():
    pass

def rescale_packlsd():
    pass

class Pack:
    """A class containing the data generated by a PackLSD run.

    This class holds the metadata and x,y,z coordinates generated by a PackLSD
    run. 

    Attributes:


    """

